name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Bootstrap
      working-directory: ${{ github.workspace }}
      run: |
        mkdir build && cd build && ../bootstrap

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: | 
        make
  
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: | 
        ./bin/ctest --output-on-failure -j4 -R '^(CMake\\.|CMakeLib\\.|RunCMake\\.ctest_memcheck)'
  
